//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shared.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AspPages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AspPages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Shared.Resources.AspPages", typeof(AspPages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have access to this resource..
        /// </summary>
        public static string AccesDenied {
            get {
                return ResourceManager.GetString("AccesDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Article.
        /// </summary>
        public static string Article {
            get {
                return ResourceManager.GetString("Article", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ChangeEmail.
        /// </summary>
        public static string ChangeEmail {
            get {
                return ResourceManager.GetString("ChangeEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change your account settings.
        /// </summary>
        public static string ChangeYourAccountSettings {
            get {
                return ResourceManager.GetString("ChangeYourAccountSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to confirm your account.
        /// </summary>
        public static string ClickHereToConfAcc {
            get {
                return ResourceManager.GetString("ClickHereToConfAcc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to logout.
        /// </summary>
        public static string ClickToLogOut {
            get {
                return ResourceManager.GetString("ClickToLogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new account..
        /// </summary>
        public static string CreateANewAcc {
            get {
                return ResourceManager.GetString("CreateANewAcc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete data and close my account.
        /// </summary>
        public static string DeletingAccount {
            get {
                return ResourceManager.GetString("DeletingAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting this data will permanently remove your account, and this cannot be recovered..
        /// </summary>
        public static string DeletingAccountData {
            get {
                return ResourceManager.GetString("DeletingAccountData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable 2FA.
        /// </summary>
        public static string Disable2FA {
            get {
                return ResourceManager.GetString("Disable2FA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Docs.
        /// </summary>
        public static string Docs {
            get {
                return ResourceManager.GetString("Docs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t have access to your authenticator device? You can.
        /// </summary>
        public static string DontHaveAccesToYourRecApp {
            get {
                return ResourceManager.GetString("DontHaveAccesToYourRecApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your email..
        /// </summary>
        public static string EnterYourEmail {
            get {
                return ResourceManager.GetString("EnterYourEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot your password?.
        /// </summary>
        public static string ForgotYourPassword {
            get {
                return ResourceManager.GetString("ForgotYourPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabling 2FA does not change the keys used in authenticator apps. If you wish to change the key used in an authenticator app you should reset your authenticator keys..
        /// </summary>
        public static string IfYouWishDisableKeys {
            get {
                return ResourceManager.GetString("IfYouWishDisableKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        public static string LogIn {
            get {
                return ResourceManager.GetString("LogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login with a recovery code.
        /// </summary>
        public static string LoginWithARecCode {
            get {
                return ResourceManager.GetString("LoginWithARecCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage your account.
        /// </summary>
        public static string ManageYourAccount {
            get {
                return ResourceManager.GetString("ManageYourAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string NickName {
            get {
                return ResourceManager.GetString("NickName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normally this would be emailed:.
        /// </summary>
        public static string NormalyWouldEmailes {
            get {
                return ResourceManager.GetString("NormalyWouldEmailes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check your email to confirm your account..
        /// </summary>
        public static string PleaseCheckEmail {
            get {
                return ResourceManager.GetString("PleaseCheckEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check your email to reset your password..
        /// </summary>
        public static string PleaseCheckEmailTOConfPassword {
            get {
                return ResourceManager.GetString("PleaseCheckEmailTOConfPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register as a new user.
        /// </summary>
        public static string RegisterAsANewUser {
            get {
                return ResourceManager.GetString("RegisterAsANewUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resend.
        /// </summary>
        public static string Resend {
            get {
                return ResourceManager.GetString("Resend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resend email confirmation.
        /// </summary>
        public static string ResendEmailConfirm {
            get {
                return ResourceManager.GetString("ResendEmailConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resety your authenticator keys..
        /// </summary>
        public static string ResetKeys {
            get {
                return ResourceManager.GetString("ResetKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset your password..
        /// </summary>
        public static string ResetYourPassword {
            get {
                return ResourceManager.GetString("ResetYourPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send email verification letter.
        /// </summary>
        public static string SendEmailVerif {
            get {
                return ResourceManager.GetString("SendEmailVerif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no external authentication services configured. See this article about setting up this ASP.NET application to support logging in via external services..
        /// </summary>
        public static string ThereAreNoExternalServices {
            get {
                return ResourceManager.GetString("ThereAreNoExternalServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This account has been locked out, please try again later..
        /// </summary>
        public static string ThisAccLockedOut {
            get {
                return ResourceManager.GetString("ThisAccLockedOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This app does not currently have a real email sender registered, see  for how to configure a real email sender..
        /// </summary>
        public static string ThisAppDoesntHave {
            get {
                return ResourceManager.GetString("ThisAppDoesntHave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This action only disables 2FA..
        /// </summary>
        public static string ThisDis2Fa {
            get {
                return ResourceManager.GetString("ThisDis2Fa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update password.
        /// </summary>
        public static string UpdatePassword {
            get {
                return ResourceManager.GetString("UpdatePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use a local account to log in..
        /// </summary>
        public static string UseALocalAccToLogin {
            get {
                return ResourceManager.GetString("UseALocalAccToLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use another service for log in..
        /// </summary>
        public static string UseAnotherServiceForLogin {
            get {
                return ResourceManager.GetString("UseAnotherServiceForLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use another service to register..
        /// </summary>
        public static string UseAnotherServiceToRegister {
            get {
                return ResourceManager.GetString("UseAnotherServiceToRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have requested to log in with a recovery code. This login will not be remembered until you provide an authenticator app code at log in or disable 2FA and log in again..
        /// </summary>
        public static string YouHaveRequestedLoginWithRecCode {
            get {
                return ResourceManager.GetString("YouHaveRequestedLoginWithRecCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have succesifaly logged out of application.
        /// </summary>
        public static string YouLoggedOut {
            get {
                return ResourceManager.GetString("YouLoggedOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your login is protected with an authenticator app. Enter your authenticator code below..
        /// </summary>
        public static string YourLoginIsProtected {
            get {
                return ResourceManager.GetString("YourLoginIsProtected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password has been reset. Please click here to log in:.
        /// </summary>
        public static string YourPasswordHaveBeenReset {
            get {
                return ResourceManager.GetString("YourPasswordHaveBeenReset", resourceCulture);
            }
        }
    }
}
